import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
} from "../assets/images/index";

//  NavBar List Start here 
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Journal",
    link: "/journal",
  },
];
// NavBarList End here 

// Special Offer data Start here
export const SplOfferData = [
  {
    _id: "201",
    img: spfOne,
    productName: "Long Beige Coat",
    price: "450.00",
    color: "Beige",
    badge: true,
    des: "Long beige coat",
  },
  {
    _id: "202",
    img: newArrFour,
    productName: "Hoodie",
    price: "350.00",
    color: "Black",
    badge: true,
    des: "Warm hoodie.",
  },
  {
    _id: "203",
    img: spfThree,
    productName: "Coat",
    price: "800.00",
    color: "Beige",
    badge: true,
    des: "Long warm coat for Winter.",
  },
  {
    _id: "204",
    img: spfFour,
    productName: "Floral Skirt",
    price: "220.00",
    color: "Floral",
    badge: true,
    des: "Floral summer skirt.",
  },
];
//Special Offer data End here 

//PaginationItems Start here 

export const paginationItems = [
  {
    _id: 1001,
    img: spfOne,
    productName: "Coat",
    price: "450.00",
    color: "Beige",
    badge: true,
    des: "Long warm Winter coat.",
  },
  {
    _id: 1002,
    img: spfTwo,
    productName: "Coat",
    price: "320.00",
    color: "Black",
    badge: true,
    des: "Warm coat.",
  },
  {
    _id: 1003,
    img: spfThree,
    productName: "Coat",
    price: "800.00",
    color: "Beige",
    badge: true,
    des: "Long warm Winter coat.",
  },
  {
    _id: 1004,
    img: spfFour,
    productName: "Floral Skirt",
    price: "220.00",
    color: "Floral",
    badge: true,
    des: "Floral Summer Skirt.",
  },
  {
    _id: 1005,
    img: bestSellerOne,
    productName: "Denims Jeans",
    price: "200.00",
    color: "Blue",
    badge: true,
    des: "Skinny high rise jeans.",
  },
  {
    _id: 1006,
    img: bestSellerTwo,
    productName: "Ladies Hand/Shoulder Bag",
    price: "220.00",
    color: "White and Blue",
    badge: false,
    des: "handbag for ladies.",
  },
  {
    _id: 1007,
    img: bestSellerThree,
    productName: "Knitted Round Neck Sweater",
    price: "289.99",
    color: "Navy and Gray",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1008,
    img: bestSellerFour,
    productName: "Travel Bag",
    price: "220.00",
    color: "Black",
    badge: false,
    des: "Knitted warm sweater or jersey.",
  },
  {
    _id: 1009,
    img: newArrOne,
    productName: "Printed T-Shirts",
    price: "150.00",
    color: "Black",
    badge: true,
    des: "Various printed tee's.",
  },
  {
    _id: 1010,
    img: newArrTwo,
    productName: "Plain T-Shirt",
    price: "100.00",
    color: "Dusty Pink",
    badge: true,
    des: "Dusty Pink t-shirt.",
  },
  {
    _id: 1011,
    img: newArrThree,
    productName: "T-Shirt",
    price: "80.00",
    color: "Mustard",
    badge: true,
    des: "Mustard t-shirt.",
  },
  {
    _id: 1012,
    img: newArrFour,
    productName: "Hoodie",
    price: "350.00",
    color: "Black",
    badge: false,
    des: "Warm hoodie.",
  },
  {
    _id: 1013,
    img: newArrTwo,
    productName: "Plain T-Shirt",
    price: "100.00",
    color: "Dusty Pink",
    badge: false,
    des: "Dusty Pink t-shirt.",
  },

  {
    _id: 1014,
    img: newArrTwo,
    productName: "Plain T-Shirt",
    price: "100.00",
    color: "Dusty Pink",
    badge: true,
    des: "Dusty Pink t-shirt.",
  },
  {
    _id: 1015,
    img: newArrFour,
    productName: "Hoodie",
    price: "350.00",
    color: "Black",
    badge: false,
    des: "Warm hoodie.",
  },
  {
    _id: 1016,
    img: newArrTwo,
    productName: "Plain T-Shirt",
    price: "100.00",
    color: "Dusty Pink",
    badge: true,
    des: "Dusty Pink t-shirt.",
  },
  {
    _id: 1017,
    img: bestSellerFour,
    productName: "Hoodie",
    price: "350.00",
    color: "Black",
    badge: false,
    des: "Warm hoodie.",
  },
  {
    _id: 1018,
    img: newArrOne,
    productName: "Printed T-Shirts",
    price: "150.00",
    color: "Various Colors",
    badge: true,
    des: "Various color of printed tee's.",
  },
  {
    _id: 1019,
    img: newArrTwo,
    productName: "Plain T-Shirt",
    price: "100.00",
    color: "Dusty Pink",
    badge: true,
    des: "Dusty Pink t-shirt.",
  },
  {
    _id: 1020,
    img: newArrThree,
    productName: "Plain T-Shirt",
    price: "80.00",
    color: "Mustard",
    badge: true,
    des: "Mustard t-shirt.",
  },
  {
    _id: 1021,
    img: spfThree,
    productName: "Coat",
    price: "800.00",
    color: "Beige",
    badge: true,
    des: "Long warm Winter coat.",
  },
  {
    _id: 1022,
    img: spfFour,
    productName: "Floral Skirt",
    price: "220.00",
    color: "Floral",
    badge: true,
    des: "Floral Summmer Skirt.",
  },
  {
    _id: 1023,
    img: bestSellerOne,
    productName: "Printed T-Shirt",
    price: "150.00",
    color: "Various",
    badge: true,
    des: "Various colors for printed tee's.",
  },
  {
    _id: 1024,
    img: spfOne,
    productName: "Denim Jeans",
    price: "200.00",
    color: "Blue",
    badge: true,
    des: "Skinny and High rise jeans.",
  },
  {
    _id: 1025,
    img: spfTwo,
    productName: "Coat",
    price: "320.00",
    color: "Black",
    badge: true,
    des: "Warm black coat.",
  },
  {
    _id: 1026,
    img: spfThree,
    productName: "Coat",
    price: "800.00",
    color: "Beige",
    badge: true,
    des: "Long warm Winter coat.",
  },
  {
    _id: 1027,
    img: spfFour,
    productName: "Floral Skirt",
    price: "220.00",
    color: "Floral",
    badge: true,
    des: "Floral Summer skirt.",
  },
  {
    _id: 1028,
    img: bestSellerOne,
    productName: "Denim Jeans",
    price: "200.00",
    color: "Blue",
    badge: true,
    des: "Skinny Jean and High rise jeans.",
  },
  {
    _id: 1029,
    img: bestSellerTwo,
    productName: "Plain T-Shirt",
    price: "100.00",
    color: "Dusty",
    badge: false,
    des: "Dusty Pink plain t-shirt.",
  },
  {
    _id: 1030,
    img: bestSellerThree,
    productName: "Plain T-Shirt",
    price: "80.00",
    color: "Mustard",
    badge: true,
    des: "Plain Mustard t-shirt.",
  },
  {
    _id: 1031,
    img: bestSellerFour,
    productName: "Hoodie",
    price: "3500.00",
    color: "Black",
    badge: false,
    des: "Warm hoodie.",
  },
  {
    _id: 1032,
    img: newArrOne,
    productName: "Printed T-Shirt",
    price: "150.00",
    color: "Various",
    badge: true,
    des: "Various colors of printed tee's.",
  },
  {
    _id: 1033,
    img: newArrTwo,
    productName: "Plain T-Shirt",
    price: "100.00",
    color: "Dusty Pink",
    badge: true,
    des: "Dusty Pink plain t-shirt.",
  },
  {
    _id: 1034,
    img: newArrThree,
    productName: "Plain T-Shirt",
    price: "80.00",
    color: "Mustard",
    badge: true,
    des: "Mustard plain t-shirt.",
  },
  {
    _id: 1035,
    img: newArrFour,
    productName: "Hoodie",
    price: "350.00",
    color: "Black",
    badge: false,
    des: "Warm hoodie.",
  },
  {
    _id: 1036,
    img: newArrTwo,
    productName: "Plain T-Shirt",
    price: "100.00",
    color: "Dusty Pink",
    badge: false,
    des: "Dusty Pink t-shirt.",
  },
  {
    _id: 1037,
    img: newArrFour,
    productName: "Hoodie",
    price: "350.00",
    color: "Black",
    badge: false,
    des: "Warm hoodie.",
  },
  {
    _id: 1038,
    img: newArrTwo,
    productName: "Plain T-Shirt",
    price: "100.00",
    color: "Dusty Pink",
    badge: true,
    des: "Dusty Pink t-shirt.",
  },
  {
    _id: 1039,
    img: bestSellerFour,
    productName: "Hoodie",
    price: "350.00",
    color: "Black",
    badge: false,
    des: "Warm hoodie.",
  },
  {
    _id: 1040,
    img: newArrOne,
    productName: "Printed T-Shirt",
    price: "150.00",
    color: "Various",
    badge: true,
    des: "Various colors of printed tee's.",
  },
  {
    _id: 1041,
    img: newArrTwo,
    productName: "Plain T-Shirt",
    price: "100.00",
    color: "Dusty Pink",
    badge: true,
    des: "Plain dusty pink t-shirt.",
  },
  {
    _id: 1042,
    img: newArrThree,
    productName: "Plain T-shirt",
    price: "80.00",
    color: "Mustard",
    badge: true,
    des: "Mustard plain t-shirt.",
  },
  {
    _id: 1043,
    img: spfThree,
    productName: "Coat",
    price: "800.00",
    color: "Beige",
    badge: true,
    des: "Long warm Winter coat.",
  },
  {
    _id: 1044,
    img: spfFour,
    productName: "Hoodie",
    price: "350.00",
    color: "Black",
    badge: true,
    des: "Warn hoodie.",
  },
  {
    _id: 1045,
    img: bestSellerOne,
    productName: "Denim Jeans",
    price: "200.00",
    color: "Blue",
    badge: true,
    des: "Skinny and high rise jeans",
  },
  {
    _id: 1046,
    img: spfOne,
    productName: "Coat",
    price: "450.00",
    color: "Beige",
    badge: true,
    des: "Long warm Winter coat.",
  },
];

